# Standard Library Chapter

Problem 1. 

Write a function that accepts a list L and returns the minimum, maximum, and average of the entries of L (in that order).  Can you implement this function in a single line?

In [80]:
# Problem 1

L = [3, 7, 2, 9, 4]
def stats(L): return (min(L), max(L), sum(L)/len(L))
print(stats(L))

(2, 9, 5.0)


Problem 2. 

Determine which of Python’s object types are mutable and which are immutable
by repeating the following experiment for an int, str, list, tuple, and set.
1. Create an object of the given type and assign a name to it.
2. Assign a new name to the first name.
3. Alter the object via only one of the names (for tuples, use my_tuple += (1,)).
4. Check to see if the two names are equal. If they are, then since changing one name
changed the other, the names refer to the same object and the object type is mutable.
Otherwise, the names refer to different objects—meaning a copy was made in step 2—and
therefore the object type is immutable.
For example, the following experiment shows that dict is a mutable type.
>>> dict_1 = {1: 'x', 2: 'b'} # Create a dictionary.
>>> dict_2 = dict_1 # Assign it a new name.
>>> dict_2[1] = 'a' # Change the 'new' dictionary.
>>> dict_1 == dict_2 # Compare the two names.
True # Both names changed!
Print a statement of your conclusions that clearly indicates which object types are mutable and
which are immutable.

In [81]:
# Problem 2

int_1 = 1
int_2 = int_1
int_2 = 2
int_1 == int_2
# False - Integers are immutable


False

In [82]:
str_1 = "Is String Immutable?"
str_2 = str_1
str_2 = "No, it is not"
str_1 == str_2
# False - Strings are immutable

False

In [83]:
list_1 = [1, 2, 3]
list_2 = list_1
list_2[0] = 4
list_1 == list_2
# True - Lists are mutable

True

In [84]:
tuple_1 = (1, 2, 3)
tuple_2 = tuple_1
tuple_2 = (4, 5, 6)
tuple_1 == tuple_2
# False - Tuples are immutable

False

In [85]:
set_1 = {1, 2, 3}
set_2 = set_1
set_2.add(4)
set_1 == set_2
# True - Sets are mutable

True

Problem 3. 

Create a module called calculator.py. Write a function that returns the sum
of two arguments and a function that returns the product of two arguments. Also use import
to add the sqrt() function from the math module to the namespace. When this file is either
run or imported, nothing should be executed.
In your solutions file, import your new custom module. Write a function that accepts two
numbers representing the lengths of the sides of a right triangle. Using only the functions from
calculator.py, calculate and return the length of the hypotenuse of the triangle.

In [86]:
# Problm 3.

import types, sys  
from math import sqrt

calculator = types.ModuleType("calculator")

def add(a, b):
    return a + b

def multiply(a, b):
    return a * b

calculator.add = add
calculator.multiply = multiply
calculator.sqrt = sqrt

sys.modules["calculator"] = calculator

In [87]:
import calculator

def hypotenuse(a, b):
    return calculator.sqrt(
        calculator.add(
            calculator.multiply(a, a),
            calculator.multiply(b, b)
        )
    )
print(hypotenuse(3, 4))

5.0


# Numpy Intro Chapter

Problem 1. 

There are two main ways to perform matrix multiplication in NumPy: with
NumPy’s dot() function (np.dot(A, B)), or with the @ operator (A @ B). Write a function
that defines the following matrices as NumPy arrays.
Return the matrix product AB.

In [88]:
# Problem 1.

import numpy as np

A = np.array([[3, -1, 4], 
              [1, 5, -9]])

B = np.array([[2, 6, -5, 3], 
              [5, -8, 9, 7], 
              [9, -3, -2, -3]])

print(np.dot(A, B))

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


Problem 2.

Write a function that defines the following matrix as a NumPy array.  Return the matrix −A3 + 9A2 − 15A.

In [89]:
import numpy as np

A = np.array([[3, 1, 4],
                  [1, 5, 9],
                  [-5, 3, 1]])
print(-A @ A @ A + 9*(A @ A) - 15*A)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Problem 5.

Write a function that defines the following matrices as NumPy arrays.  Use NumPy’s stacking functions to create and return the block matrix: where I is the 3 × 3 identity matrix and each 0 is a matrix of all zeros of appropriate size.
A block matrix of this form is used in the Interior Point method for linear optimization.

In [90]:
import numpy as np

def problem5():
    A = np.array([[0, 2, 4],
                  [1, 3, 5]])
    B = np.array([[3, 0, 0],
                  [3, 3, 0],
                  [3, 3, 3]])
    C = -2 * np.eye(3, dtype=int)
    I = np.eye(3, dtype=int)

    # zeros of the needed sizes
    Z33 = np.zeros((3,3), dtype=int)
    Z22 = np.zeros((2,2), dtype=int)
    Z23 = np.zeros((2,3), dtype=int)
    Z32 = np.zeros((3,2), dtype=int)

    # Block matrix:
    # [ 0   A^T  I
    #   A    0   0
    #   B    0   C ]
    M = np.block([
        [Z33, A.T, I],
        [A,   Z22, Z23],
        [B,   Z32, C]
    ])
    return M

# Example: print result
M = problem5()
print(M)
print("shape:", M.shape)   # (8, 8)

[[ 0  0  0  0  1  1  0  0]
 [ 0  0  0  2  3  0  1  0]
 [ 0  0  0  4  5  0  0  1]
 [ 0  2  4  0  0  0  0  0]
 [ 1  3  5  0  0  0  0  0]
 [ 3  0  0  0  0 -2  0  0]
 [ 3  3  0  0  0  0 -2  0]
 [ 3  3  3  0  0  0  0 -2]]
shape: (8, 8)


# Object Oriented Chapter

Problem 1. 

Expand the Backpack class to match the following specifications.
1. Modify the constructor so that it accepts three total arguments: name, color, and
max_size (in that order). Make max_size a keyword argument that defaults to 5. Store
each input as an attribute.
2. Modify the put() method to check that the backpack does not go over capacity. If there
are already max_size items or more, print “No Room!” and do not add the item to the
contents list.
3. Write a new method called dump() that resets the contents of the backpack to an empty
list. This method should not receive any arguments (except self).
4. Documentation is especially important in classes so that the user knows what an ob-
ject’s attributes represent and how to use methods appropriately. Update (or write) the
docstrings for the __init__(), put(), and dump() methods, as well as the actual class
docstring (under class but before __init__()) to reflect the changes from parts 1-3 of
this problem.
To ensure that your class works properly, write a test function outside outside of the
Backpack class that instantiates and analyzes a Backpack object.

In [79]:
class Backpack:

    def __init__(self, name, color, max_size=5):
        """Constructor: make a backpack with a name, color, and max size."""
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []

    def put(self, item):
        """Put an item in the backpack if there is room."""
        if len(self.contents) >= self.max_size:
            print("No Room!")
        else:
            self.contents.append(item)

    def take(self, item):
        """Take an item out of the backpack if it is there."""
        if item in self.contents:
            self.contents.remove(item)

    def dump(self):
        """Empty everything out of the backpack."""
        self.contents = []

def test_backpack():
    testpack = Backpack("Barry", "black")

    if testpack.name != "Barry":
        print("Backpack.name assigned incorrectly")

    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)

    print("Contents:", testpack.contents)

    testpack.take("pen")
    print("After taking pen:", testpack.contents)

    testpack.dump()
    print("After dump:", testpack.contents)

test_backpack()

Contents: ['pencil', 'pen', 'paper', 'computer']
After taking pen: ['pencil', 'paper', 'computer']
After dump: []


Problem 2.

Write a Jetpack class that inherits from the Backpack class.
1. Override the constructor so that in addition to a name, color, and maximum size, it also
accepts an amount of fuel. Change the default value of max_size to 2, and set the default
value of fuel to 10. Store the fuel as an attribute.
2. Add a fly() method that accepts an amount of fuel to be burned and decrements the
fuel attribute by that amount. If the user tries to burn more fuel than remains, print “Not
enough fuel!” and do not decrement the fuel.
3. Override the dump() method so that both the contents and the fuel tank are emptied.
4. Write clear, detailed docstrings for the class and each of its methods

In [91]:
class Jetpack(Backpack):
    # Define the Jetpack class here.  Subnclass of Backpack
    def __init__(self, name, color, max_size=2, fuel=10):
        super().__init__(name, color, max_size)
        self.fuel = fuel
    # Define the fly and dump methods here + fuel limits
    def fly(self, burn):
        if burn > self.fuel:
            print("Not enough fuel!")
        else:
            self.fuel -= burn

    def dump(self):
        super().dump()
        self.fuel = 0